### ISSUE TITLE
Pump basal profile editor weirdness

### ISSUE THREAD

**Issue by jronnberg** [timomer/HAPP#48]
In the Animas Vibe pump the basal is set in steps of 0.025 U/h. Hence it is possible to set the basal to, for example, 0.425U/h. When I try to enter that value in HAPP  it get exchanged for 425.0U/h.
This is with version Code: 47 Name: 1.4.1

If HAPP can not use more that 2 decimals it should round the number not multiply it by 100.

And a wish: it would be great if HAPP could fetch the basal profil from NightScout and also react to and even generate Profile Switch events. Perhaps that needs to made optional but I know I would use it.

**Comment by Mondelman** [comment]
Try changing "." by ","
It may work..

Miguel Ten
+34 676 35 38 37

**Comment by jronnberg** [comment]
When I try typing "," the keyboard (while I'm in the editor) does not respond. The only possibility is to use ".".

**Comment by Mondelman** [comment]
Try changing language. It worked for me when choosing Spanish keyboard.

**Comment by timomer** [comment]
Hi @jronnberg ,

In the profile editor, what value is saved? Where do you see 0.025 getting converted to 425.0? What region is your phone set too?

@Mondelman what issue did you have? Not being able to use ","? Is your Region settings Spanish? 

Nightscout feature - I plan a complete rewrite of this integration as its very basic right now. Please open a new feature request with what you want, I am interested in more details on what you mean by Profile Switch events.

**Comment by jronnberg** [comment]
Hi

My phone language is set to Swedish/Svenska.
If I type in 0.425 and hit save and reopen the editor it was saved as 425.0.
The change to 425.0 happens immediately if I type in 0.425 and hit the + to add a new row.

If I change the language to English (United States) this does not happen, then the value 0.425 is saved.
Hence, I have been able to input the correct basal profile by using English while I'm editing.

A related minor issue it that at the main screen the current basal rate is displayed with 2 decimals only.
Hence it looks like the basal is 0.42 instead of 0.425

**Comment by timomer** [comment]
ok, for the display issue go to settings > precision rounding 

I think the issue is with the function that takes user decimal inputs (strings) and converts to true decimal. 
https://github.com/timomer/HAPP/blob/master/app/src/main/java/com/hypodiabetic/happ/tools.java#L281

Ill fire up a VM and test, keen to get this fixed as its a nasty bug

**Comment by jronnberg** [comment]
I already have the precision rounding set and it displays BGs (eventual and snooze),  IoB and CoB with 2 decimals if needed but in the top (under Default Basal) it says 0% (0.42U/h) not 0% (0.425U/h) as I would expect when I have managed to enter that rate in the profile.

**Comment by timomer** [comment]
Yes, ill get that addressed, its just a display thing

**Comment by timomer** [comment]
Yep, the issue is with the said function. For whatever reason the Locale sv is converting to an Integer, see screen grabs of en-us and sv Locale
![image](https://cloud.githubusercontent.com/assets/5235732/21941699/58109b10-d9ca-11e6-999c-4057484aa532.png)

![image](https://cloud.githubusercontent.com/assets/5235732/21941716/6dc59366-d9ca-11e6-9da8-d6bf4fb3abc9.png)

Android appears to be a right pain with different Locales, I have adjusted the code. Appears fine for UK, DE and Swedish. Also Precision Rounding updated to support Basal to 3 decimal places. 

https://drive.google.com/file/d/0BxE8lMx4AjLiU1k2TTBiSndaZlk/view?usp=sharing

**Comment by jronnberg** [comment]
Thanks for fixing it so quickly.
I can confirm that it now work for me.

**Comment by jronnberg** [comment]
Hi @timomer 
Can I bother you to post the changes here. I would like apply them to my own repo that I just forked from the master branch.
I intend to play around a bit and see if I can be of any help by trying to solve a few minor issues I've seen and I would like to have these fixes as well.

**Comment by timomer** [comment]
just pushed to Dev https://github.com/timomer/HAPP/commit/135e731bf3350f513afdc10d968962982de127bf

FYI - I am in the process of a complete code review of HAPP, making it more modular, will be much easier to work with. Ill be posting code in the next few days, maybe this weekend
