### ISSUE TITLE
HAPP crash

### ISSUE THREAD

**Issue by ToreBj** [timomer/HAPP#53]
Hi ,

I have experienced crash a few times lately. Providing the log. It seems to continue after this.
[HAPP crash.txt](https://github.com/timomer/HAPP/files/810154/HAPP.crash.txt)
 

Br Tore

**Comment by timomer** [comment]
Thanks ToreBj, unfortunately the LogCat shows logs for after the crash, difficult to get the logs at time of crash unless you have your device plugged into Android Studio.

Ill check Crash Analytics for new crashes, im guessing this is due to a know Realm issue where a Realm object is accessed when the connection is closed, this appears as a random crash that happens only now and then when loading UI. This is being fixed.

Will close for now, please reopen if you get anymore details
