### ISSUE TITLE
App to drive the pump

### ISSUE THREAD

**Issue by davidmlb** [timomer/HAPP#62]
Hi, I'using the HAPP to sugest my pump basals. but every time I Whant to change the basal i need to do it manually on the pump, there are some app to send directly tha basal to my pump? I have a medtronic minimed 

regards

**Comment by timomer** [comment]
Hi,

HAPP is Open Loop by design, so it will notify when an adjustment is needed for you to manually action.

I have added the ability to send these notifications to external apps that then can action them for you if they can talk to your pump, this keeps HAPP design more simple by focusing on APS. These apps are called Pump Driver Apps, there is a Medtronic and Dana R one in the works but is on hold due to lack of time, if progress is made I will make an announcement.

Roch Combo is also in the works and maybe useable soon.
