### ISSUE TITLE
maxSafeBasal setting

### ISSUE THREAD

**Issue by jrussell88** [timomer/HAPP#65]
I'm running openaps_ore0_master on Android Nougat; Freestyle Libre, Glimp, Nightscout and NSClient. 

I've set:
- APS Settings - Limits - Max Basal=10, and MaxBasalIOB =16
- Pump Settings - Pump General - Max Bolus=16

If I'm running high, and need a correction, HAPP reports for example:
"Eventual BG 156 > 126.127,adj. req. rate: 2.801 to maxSafeBasal:2.100,no temp,setting 2.09...96U/hr"
where the maxSafeBasal is limiting the correction despite my settings. 

Where can I change this? 

Thanks!

**Comment by timomer** [comment]
Hey,

Sorry for my late reply, oref0 has a hard coded limit, that you can see here: 
https://github.com/timomer/HAPP/blob/master/app/src/main/assets/openaps/master/oref0/lib/determine-basal/determine-basal.js#L239

This is 4 * Current Basal or 3 * the Max Hourly Basal you have set.

This is by design for oref0, if you would like to change this just edit this line highlighted and compile in Android Studio.

please reopen if you have any more questions!
