### ISSUE TITLE
Carb & bolus data not showing in HAPP

### ISSUE THREAD

**Issue by SyGrOvE** [timomer/HAPP#66]
Hi. I've just downloaded & started using HAPP last night, but treatments that I've not entered directly through HAPP aren't showing. 
I've been using xdrip+ with dexcom g4 for ages & have a nightscout site. I usually enter carbs & boluses either with xdrip+ on my phone or through careportal on my Pebble. 

Another thing i've noticed is that these entries now appear twice in xdrip if I put them through careportal or enter them into HAPP directly. I end up with double the IOB in xdrip & it messes up the xdrip predictive algorithm. 
I've tried switching cgm data source between xdrip & NSclient, & both options are turned on in the nightscout via NSclient integration settings. 
Any ideas of what i'm doing wrong?

**Comment by timomer** [comment]
Hey,

HAPP only supports entering treatments directly in the app and can then send them to Nightscout if configured. As of now, this is only one way, there is no way to sync this into HAPP.

If you are using xDrip, I suggest using that as your CGM source. If you wish to use HAPP, treatments must be entered in HAPP and then will be Synced to Nightscout and then xDrip+ etc if that's what you have setup.

I am planning a much more feature rich sync process for HAPP+, this is just in design as of right now and I plan to pick up the project when winter hits.

Please reopen if this does not cover your questions?

**Comment by CaroGo** [comment]
I use HAPP and xdrip+ and the nightscout site... I can enter treatments either in HAPP or in xdrip+ or via the careportal on the pebble watch... no problems. All treatments are shown on the nightscout site. As cgm source I selected xdrip+. That works fine for me...no double treatments... everything in place!

**Comment by SyGrOvE** [comment]
I have changed cgm data source to xdrip & am now entering all carbs & boluses through HAPP, but am still getting 2 entries in xdrip for 1 event. I've noticed these are 2 minutes apart. Could both HAPP and either NS or NSclient be sending them to xdrip, with a 2min delay based on the time for NS/NSclient to process the information from HAPP?

**Comment by timomer** [comment]
@CaroGo is you enter treatments into xdrip / nightscout, HAPP will not be aware of them so cannot use them for the OpenAPS algorithm. 

@SyGrOvE HAPP will be syncing them to NSClient, can you check NSClient logs and see how many treatments it is receiving from HAPP? This will confirm if the issue is coming from HAPP or with NSClient \ xDrip+

**Comment by SyGrOvE** [comment]
The teatments aren't duplicated in NSclient.

**Comment by CaroGo** [comment]
@timomer:Yes, that's right! :-/ But no duplicates on Nightscout. And all treatments are shown correctly....

**Comment by timomer** [comment]
@CaroGo yep, just wanted to be sure you were aware :)

@SyGrOvE if that's the case then the issue is not HAPP as NSClient only receives one treatment. If you get two treatments in Nightscout, I would investigate with NSClient to see how many treatments it is sending. If its only in xDrip+ then something must be happening in xDrip+. Not sure what logging there is in xDrip+ that may provide more details?

**Comment by SyGrOvE** [comment]
Ok, thanks for your help.
